; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
lib_deps =
	olikraus/Ucglib@^1.5.2
	olikraus/U8g2@^2.36.4
	Wire
	janelia-arduino/TMC2209@^10.1.1
    gin66/FastAccelStepper@^1.2.5
    madhephaestus/ESP32Servo@^3.1.3
upload_speed = 460800
monitor_speed = 460800

[env:lolin_c3_mini_ota]
extends = env:lolin_c3_mini
upload_protocol = espota
upload_port = steppertest.local
; If OTA_PASSWORD in include/ota_secrets.h is non-empty, uncomment and set:
; upload_flags =
;     --auth=your-ota-password
